# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e964012ea864a2ffd72619865a010309b6183211ced2bd5c91f37ed7b5c74b49eceb0a0777e8e5f4f1fdac9ae7a691737ff4244fe129348f2e9f67be5f68637

test:
  secret_key_base: 49b941ef17416fc3b89740becb4613785356f1adaafc9b459a7deed831e38aa48c72405997d5202caf72bf3c5bae57fa576376d5be15597506b252c6b6281000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
